services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # TCP - messages between services
      - "15672:15672" # UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
