# Variables
@baseUrl = http://localhost:3333
# @baseUrl = http://localhost:8000/orders   # API gateway baseUrl

###

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

POST {{baseUrl}}/orders
Content-Type: application/json

{
  "amount": 1
}
