_format_version: "3.0"
_transform: true

services:
  - name: orders
    # V1, with docker-compose and config.yaml:
    # url: http://host.docker.internal:3333
    # V2, with docker-compose building the image from Dockerfile as per config.template.yaml:
    url: ${ORDERS_SERVICE_URL}
    # Not needed:
    # protocol: http
    # host: host.docker.internal
    # port: 3333
    # Not used:
    # connect_timeout: 10000  # 10s
    # retries: 3
    # Available paths:
    # path: /orders
    # Or:
    path: /
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - /orders

  - name: invoices
    url: http://host.docker.internal:3334
    # protocol: http
    # host: host.docker.internal
    # port: 3334
    path: /
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - /invoices

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization